
    create table course (
       id_course int4 generated by default as identity,
        schedule_day varchar(30) not null,
        description varchar(1000) not null,
        max_students int4 not null,
        schedule_module varchar(30) not null,
        name varchar(250) not null,
        id_teacher int4,
        primary key (id_course)
    )

    create table enrollment (
       id_student int4 not null,
        id_course int4 not null,
        primary key (id_student, id_course)
    )

    create table role (
       id_role int4 generated by default as identity,
        role varchar(50) not null,
        primary key (id_role)
    )

    create table student (
       id_student int4 generated by default as identity,
        dni varchar(50) not null,
        email varchar(150) not null,
        last_name varchar(250) not null,
        name varchar(150) not null,
        id_user int4,
        primary key (id_student)
    )

    create table teacher (
       id_teacher int4 generated by default as identity,
        dni varchar(50) not null,
        last_name varchar(250) not null,
        name varchar(150) not null,
        status varchar(20) not null,
        primary key (id_teacher)
    )

    create table user_entity (
       id_user int4 generated by default as identity,
        password varchar(250) not null,
        username varchar(50) not null,
        primary key (id_user)
    )

    create table user_roles (
       id_user int4 not null,
        id_role int4 not null,
        primary key (id_user, id_role)
    )

    alter table if exists course 
       add constraint FKqey4eoh5x4ci13g401v7gxn8c 
       foreign key (id_teacher) 
       references teacher

    alter table if exists enrollment 
       add constraint FK5w3l83aj53f650exh6nrqyt97 
       foreign key (id_course) 
       references course

    alter table if exists enrollment 
       add constraint FKimfvrjges6x616qv5tqdsxqsu 
       foreign key (id_student) 
       references student

    alter table if exists student 
       add constraint FKrrlgm1dmpw7sr8kaap1ry5irv 
       foreign key (id_user) 
       references user_entity

    alter table if exists user_roles 
       add constraint FKrcmv344t6l0beetcs8u4xhpd 
       foreign key (id_role) 
       references role

    alter table if exists user_roles 
       add constraint FKbe3md5dpb2637ym9erdtjqayl 
       foreign key (id_user) 
       references user_entity
